{"payload":{"allShortcutsEnabled":true,"fileTree":{"Reports":{"items":[{"name":"images","path":"Reports/images","contentType":"directory"},{"name":"biblio.bib","path":"Reports/biblio.bib","contentType":"file"},{"name":"james2023evaluating.tex","path":"Reports/james2023evaluating.tex","contentType":"file"},{"name":"liu2014effects.tex","path":"Reports/liu2014effects.tex","contentType":"file"},{"name":"liu2016shared.tex","path":"Reports/liu2016shared.tex","contentType":"file"},{"name":"liu2017coreach.tex","path":"Reports/liu2017coreach.tex","contentType":"file"},{"name":"main.aux","path":"Reports/main.aux","contentType":"file"},{"name":"main.bbl","path":"Reports/main.bbl","contentType":"file"},{"name":"main.bcf","path":"Reports/main.bcf","contentType":"file"},{"name":"main.blg","path":"Reports/main.blg","contentType":"file"},{"name":"main.fdb_latexmk","path":"Reports/main.fdb_latexmk","contentType":"file"},{"name":"main.fls","path":"Reports/main.fls","contentType":"file"},{"name":"main.log","path":"Reports/main.log","contentType":"file"},{"name":"main.out","path":"Reports/main.out","contentType":"file"},{"name":"main.pdf","path":"Reports/main.pdf","contentType":"file"},{"name":"main.run.xml","path":"Reports/main.run.xml","contentType":"file"},{"name":"main.synctex.gz","path":"Reports/main.synctex.gz","contentType":"file"},{"name":"main.tex","path":"Reports/main.tex","contentType":"file"}],"totalCount":18},"":{"items":[{"name":"Code","path":"Code","contentType":"directory"},{"name":"Reports","path":"Reports","contentType":"directory"},{"name":"README.md","path":"README.md","contentType":"file"}],"totalCount":3}},"fileTreeProcessingTime":9.135499,"foldersToFetch":[],"reducedMotionEnabled":"system","repo":{"id":635200149,"defaultBranch":"main","name":"WallVR","ownerLogin":"Jvaljer","currentUserCanPush":true,"isFork":false,"isEmpty":false,"createdAt":"2023-05-02T09:21:24.000+02:00","ownerAvatar":"https://avatars.githubusercontent.com/u/98323161?v=4","public":true,"private":false,"isOrgOwned":false},"symbolsExpanded":true,"treeExpanded":true,"refInfo":{"name":"main","listCacheKey":"v0:1683012368.0","canEdit":true,"refType":"branch","currentOid":"14cb5b0b1de9ca0a9a2423f87b4b6dcdafd63754"},"path":"Reports/main.run.xml","currentUser":{"id":98323161,"login":"Jvaljer","userEmail":"abbel.haol@gmail.com"},"blob":{"rawLines":["<?xml version=\"1.0\" standalone=\"yes\"?>","<!-- logreq request file -->","<!-- logreq version 1.0 / dtd version 1.0 -->","<!-- Do not edit this file! -->","<!DOCTYPE requests [","  <!ELEMENT requests (internal | external)*>","  <!ELEMENT internal (generic, (provides | requires)*)>","  <!ELEMENT external (generic, cmdline?, input?, output?, (provides | requires)*)>","  <!ELEMENT cmdline (binary, (option | infile | outfile)*)>","  <!ELEMENT input (file)+>","  <!ELEMENT output (file)+>","  <!ELEMENT provides (file)+>","  <!ELEMENT requires (file)+>","  <!ELEMENT generic (#PCDATA)>","  <!ELEMENT binary (#PCDATA)>","  <!ELEMENT option (#PCDATA)>","  <!ELEMENT infile (#PCDATA)>","  <!ELEMENT outfile (#PCDATA)>","  <!ELEMENT file (#PCDATA)>","  <!ATTLIST requests","    version CDATA #REQUIRED","  >","  <!ATTLIST internal","    package CDATA #REQUIRED","    priority (9) #REQUIRED","    active (0 | 1) #REQUIRED","  >","  <!ATTLIST external","    package CDATA #REQUIRED","    priority (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #REQUIRED","    active (0 | 1) #REQUIRED","  >","  <!ATTLIST provides","    type (static | dynamic | editable) #REQUIRED","  >","  <!ATTLIST requires","    type (static | dynamic | editable) #REQUIRED","  >","  <!ATTLIST file","    type CDATA #IMPLIED","  >","]>","<requests version=\"1.0\">","  <internal package=\"biblatex\" priority=\"9\" active=\"1\">","    <generic>latex</generic>","    <provides type=\"dynamic\">","      <file>main.bcf</file>","    </provides>","    <requires type=\"dynamic\">","      <file>main.bbl</file>","    </requires>","    <requires type=\"static\">","      <file>blx-dm.def</file>","      <file>blx-compat.def</file>","      <file>biblatex.def</file>","      <file>standard.bbx</file>","      <file>numeric.bbx</file>","      <file>numeric.cbx</file>","      <file>biblatex.cfg</file>","      <file>english.lbx</file>","      <file>french.lbx</file>","    </requires>","  </internal>","  <external package=\"biblatex\" priority=\"5\" active=\"1\">","    <generic>biber</generic>","    <cmdline>","      <binary>biber</binary>","      <infile>main</infile>","    </cmdline>","    <input>","      <file>main.bcf</file>","    </input>","    <output>","      <file>main.bbl</file>","    </output>","    <provides type=\"dynamic\">","      <file>main.bbl</file>","    </provides>","    <requires type=\"dynamic\">","      <file>main.bcf</file>","    </requires>","  </external>","</requests>"],"stylingDirectives":[[{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":13,"cssClass":"pl-e"},{"start":14,"end":19,"cssClass":"pl-s"},{"start":14,"end":15,"cssClass":"pl-pds"},{"start":18,"end":19,"cssClass":"pl-pds"},{"start":19,"end":30,"cssClass":"pl-e"},{"start":31,"end":36,"cssClass":"pl-s"},{"start":31,"end":32,"cssClass":"pl-pds"},{"start":35,"end":36,"cssClass":"pl-pds"}],[{"start":0,"end":28,"cssClass":"pl-c"},{"start":0,"end":4,"cssClass":"pl-c"},{"start":25,"end":28,"cssClass":"pl-c"}],[{"start":0,"end":45,"cssClass":"pl-c"},{"start":0,"end":4,"cssClass":"pl-c"},{"start":42,"end":45,"cssClass":"pl-c"}],[{"start":0,"end":31,"cssClass":"pl-c"},{"start":0,"end":4,"cssClass":"pl-c"},{"start":28,"end":31,"cssClass":"pl-c"}],[{"start":2,"end":9,"cssClass":"pl-ent"},{"start":10,"end":18,"cssClass":"pl-e"}],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[{"start":1,"end":9,"cssClass":"pl-ent"},{"start":10,"end":17,"cssClass":"pl-e"},{"start":18,"end":23,"cssClass":"pl-s"},{"start":18,"end":19,"cssClass":"pl-pds"},{"start":22,"end":23,"cssClass":"pl-pds"}],[{"start":3,"end":11,"cssClass":"pl-ent"},{"start":12,"end":19,"cssClass":"pl-e"},{"start":20,"end":30,"cssClass":"pl-s"},{"start":20,"end":21,"cssClass":"pl-pds"},{"start":29,"end":30,"cssClass":"pl-pds"},{"start":31,"end":39,"cssClass":"pl-e"},{"start":40,"end":43,"cssClass":"pl-s"},{"start":40,"end":41,"cssClass":"pl-pds"},{"start":42,"end":43,"cssClass":"pl-pds"},{"start":44,"end":50,"cssClass":"pl-e"},{"start":51,"end":54,"cssClass":"pl-s"},{"start":51,"end":52,"cssClass":"pl-pds"},{"start":53,"end":54,"cssClass":"pl-pds"}],[{"start":5,"end":12,"cssClass":"pl-ent"},{"start":20,"end":27,"cssClass":"pl-ent"}],[{"start":5,"end":13,"cssClass":"pl-ent"},{"start":14,"end":18,"cssClass":"pl-e"},{"start":19,"end":28,"cssClass":"pl-s"},{"start":19,"end":20,"cssClass":"pl-pds"},{"start":27,"end":28,"cssClass":"pl-pds"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":22,"end":26,"cssClass":"pl-ent"}],[{"start":6,"end":14,"cssClass":"pl-ent"}],[{"start":5,"end":13,"cssClass":"pl-ent"},{"start":14,"end":18,"cssClass":"pl-e"},{"start":19,"end":28,"cssClass":"pl-s"},{"start":19,"end":20,"cssClass":"pl-pds"},{"start":27,"end":28,"cssClass":"pl-pds"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":22,"end":26,"cssClass":"pl-ent"}],[{"start":6,"end":14,"cssClass":"pl-ent"}],[{"start":5,"end":13,"cssClass":"pl-ent"},{"start":14,"end":18,"cssClass":"pl-e"},{"start":19,"end":27,"cssClass":"pl-s"},{"start":19,"end":20,"cssClass":"pl-pds"},{"start":26,"end":27,"cssClass":"pl-pds"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":24,"end":28,"cssClass":"pl-ent"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":28,"end":32,"cssClass":"pl-ent"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":26,"end":30,"cssClass":"pl-ent"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":26,"end":30,"cssClass":"pl-ent"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":25,"end":29,"cssClass":"pl-ent"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":25,"end":29,"cssClass":"pl-ent"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":26,"end":30,"cssClass":"pl-ent"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":25,"end":29,"cssClass":"pl-ent"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":24,"end":28,"cssClass":"pl-ent"}],[{"start":6,"end":14,"cssClass":"pl-ent"}],[{"start":4,"end":12,"cssClass":"pl-ent"}],[{"start":3,"end":11,"cssClass":"pl-ent"},{"start":12,"end":19,"cssClass":"pl-e"},{"start":20,"end":30,"cssClass":"pl-s"},{"start":20,"end":21,"cssClass":"pl-pds"},{"start":29,"end":30,"cssClass":"pl-pds"},{"start":31,"end":39,"cssClass":"pl-e"},{"start":40,"end":43,"cssClass":"pl-s"},{"start":40,"end":41,"cssClass":"pl-pds"},{"start":42,"end":43,"cssClass":"pl-pds"},{"start":44,"end":50,"cssClass":"pl-e"},{"start":51,"end":54,"cssClass":"pl-s"},{"start":51,"end":52,"cssClass":"pl-pds"},{"start":53,"end":54,"cssClass":"pl-pds"}],[{"start":5,"end":12,"cssClass":"pl-ent"},{"start":20,"end":27,"cssClass":"pl-ent"}],[{"start":5,"end":12,"cssClass":"pl-ent"}],[{"start":7,"end":13,"cssClass":"pl-ent"},{"start":21,"end":27,"cssClass":"pl-ent"}],[{"start":7,"end":13,"cssClass":"pl-ent"},{"start":20,"end":26,"cssClass":"pl-ent"}],[{"start":6,"end":13,"cssClass":"pl-ent"}],[{"start":5,"end":10,"cssClass":"pl-ent"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":22,"end":26,"cssClass":"pl-ent"}],[{"start":6,"end":11,"cssClass":"pl-ent"}],[{"start":5,"end":11,"cssClass":"pl-ent"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":22,"end":26,"cssClass":"pl-ent"}],[{"start":6,"end":12,"cssClass":"pl-ent"}],[{"start":5,"end":13,"cssClass":"pl-ent"},{"start":14,"end":18,"cssClass":"pl-e"},{"start":19,"end":28,"cssClass":"pl-s"},{"start":19,"end":20,"cssClass":"pl-pds"},{"start":27,"end":28,"cssClass":"pl-pds"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":22,"end":26,"cssClass":"pl-ent"}],[{"start":6,"end":14,"cssClass":"pl-ent"}],[{"start":5,"end":13,"cssClass":"pl-ent"},{"start":14,"end":18,"cssClass":"pl-e"},{"start":19,"end":28,"cssClass":"pl-s"},{"start":19,"end":20,"cssClass":"pl-pds"},{"start":27,"end":28,"cssClass":"pl-pds"}],[{"start":7,"end":11,"cssClass":"pl-ent"},{"start":22,"end":26,"cssClass":"pl-ent"}],[{"start":6,"end":14,"cssClass":"pl-ent"}],[{"start":4,"end":12,"cssClass":"pl-ent"}],[{"start":2,"end":10,"cssClass":"pl-ent"}]],"csv":null,"csvError":null,"dependabotInfo":{"showConfigurationBanner":null,"configFilePath":null,"networkDependabotPath":"/Jvaljer/WallVR/network/updates","dismissConfigurationNoticePath":"/settings/dismiss-notice/dependabot_configuration_notice","configurationNoticeDismissed":false,"repoAlertsPath":"/Jvaljer/WallVR/security/dependabot","repoSecurityAndAnalysisPath":"/Jvaljer/WallVR/settings/security_analysis","repoOwnerIsOrg":false,"currentUserCanAdminRepo":true},"displayName":"main.run.xml","displayUrl":"https://github.com/Jvaljer/WallVR/blob/main/Reports/main.run.xml?raw=true","headerInfo":{"blobSize":"2.2 KB","deleteInfo":{"deleteTooltip":"Delete this file"},"editInfo":{"editTooltip":"Edit this file"},"ghDesktopPath":"x-github-client://openRepo/https://github.com/Jvaljer/WallVR?branch=main&filepath=Reports%2Fmain.run.xml","gitLfsPath":null,"onBranch":true,"shortPath":"0877e53","siteNavLoginPath":"/login?return_to=https%3A%2F%2Fgithub.com%2FJvaljer%2FWallVR%2Fblob%2Fmain%2FReports%2Fmain.run.xml","isCSV":false,"isRichtext":false,"toc":null,"lineInfo":{"truncatedLoc":"83","truncatedSloc":"83"},"mode":"file"},"image":false,"isCodeownersFile":null,"isPlain":false,"isValidLegacyIssueTemplate":false,"issueTemplateHelpUrl":"https://docs.github.com/articles/about-issue-and-pull-request-templates","issueTemplate":null,"discussionTemplate":null,"language":"XML","languageID":399,"large":false,"loggedIn":true,"newDiscussionPath":"/Jvaljer/WallVR/discussions/new","newIssuePath":"/Jvaljer/WallVR/issues/new","planSupportInfo":{"repoIsFork":null,"repoOwnedByCurrentUser":null,"requestFullPath":"/Jvaljer/WallVR/blob/main/Reports/main.run.xml","showFreeOrgGatedFeatureMessage":null,"showPlanSupportBanner":null,"upgradeDataAttributes":null,"upgradePath":null},"publishBannersInfo":{"dismissActionNoticePath":"/settings/dismiss-notice/publish_action_from_dockerfile","dismissStackNoticePath":"/settings/dismiss-notice/publish_stack_from_file","releasePath":"/Jvaljer/WallVR/releases/new?marketplace=true","showPublishActionBanner":false,"showPublishStackBanner":false},"rawBlobUrl":"https://github.com/Jvaljer/WallVR/raw/main/Reports/main.run.xml","renderImageOrRaw":false,"richText":null,"renderedFileInfo":null,"shortPath":null,"tabSize":8,"topBannersInfo":{"overridingGlobalFundingFile":false,"globalPreferredFundingPath":null,"repoOwner":"Jvaljer","repoName":"WallVR","showInvalidCitationWarning":false,"citationHelpUrl":"https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files","showDependabotConfigurationBanner":null,"actionsOnboardingTip":null},"truncated":false,"viewable":true,"workflowRedirectUrl":null,"symbols":{"timedOut":false,"notAnalyzed":true,"symbols":[]}},"copilotInfo":{"documentationUrl":"https://docs.github.com/copilot/overview-of-github-copilot/about-github-copilot-for-individuals","notices":{"codeViewPopover":{"dismissed":false,"dismissPath":"/settings/dismiss-notice/code_view_copilot_popover"}},"userAccess":{"accessAllowed":false,"hasSubscriptionEnded":false,"orgHasCFBAccess":false,"userHasCFIAccess":false,"userHasOrgs":false,"userIsOrgAdmin":false,"userIsOrgMember":false,"business":null,"featureRequestInfo":null}},"copilotAccessAllowed":false,"csrf_tokens":{"/Jvaljer/WallVR/branches":{"post":"g3l15GF2cWq8b2aM6BxoNVf13tbs8KkIpi36cbA8YCBTRlVGsAlmmpppOAk704Z74fkC0g8hSK7O7EDsV5Gvgw"},"/repos/preferences":{"post":"AHRGfx5jsr8WNcu6x7uyOukLIDyNt9J4f4ICxhFdYjxMGhUetfAxW_7aYzMg_ojNWQQWG9sO0pvDzCHgjvIDXw"}}},"title":"WallVR/Reports/main.run.xml at main · Jvaljer/WallVR"}